# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0006_postponedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
