# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0007_postponedpost_is_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostponedPostResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='postponedpost',
            name='is_sent',
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='description',
            field=models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u043b\u043e\u0436\u0435\u043d\u0438\u044f/\u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='send_at',
            field=models.DateTimeField(verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u0432'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='postponedpostresult',
            name='postponed_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.PostponedPost'),
        ),
    ]
