# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0010_botadministratorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botadministratorprofile',
            name='telegram_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botadministratorprofile',
            name='telegram_token_test',
            field=models.CharField(help_text='\u0422\u043e\u043a\u0435\u043d \u0442\u0435\u043b\u0435\u0433\u0440\u0430\u043c\u043c\u0430 \u0434\u043b\u044f \u0442\u0435\u0441\u0442\u0440\u043e\u0432\u0430\u043d\u0438\u044f', max_length=255, null=True),
        ),
    ]
