# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0012_auto_20170220_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='botadministratorprofile',
            name='bot_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
