# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0013_botadministratorprofile_bot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_bot_for_testing', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='botadministratorprofile',
            name='bot_name',
        ),
        migrations.RemoveField(
            model_name='botadministratorprofile',
            name='telegram_token',
        ),
        migrations.RemoveField(
            model_name='botadministratorprofile',
            name='telegram_token_test',
        ),
        migrations.AddField(
            model_name='bot',
            name='administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.BotAdministratorProfile'),
        ),
    ]
