# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0016_catalog_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Buyer',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='customer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='postponedpostresult',
            old_name='customer',
            new_name='buyer',
        ),
    ]
