# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0017_auto_20170302_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotBuyerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_buyer_map_rel', to='shop_bot_app.Bot')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_buyer_map_rel', to='shop_bot_app.Buyer')),
            ],
        ),
    ]
