# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0018_botbuyermap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='chat_id',
            new_name='telegram_user_id',
        ),
    ]
