# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0021_auto_20170304_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=1000)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Bot')),
            ],
        ),
    ]
