# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0022_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
