# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 16:25
from __future__ import unicode_literals

from django.contrib.auth.models import User, Group
from shop_bot_app.models import Bot, BotAdministratorProfile

from django.db import migrations


def create_bot_administrator(apps, schema_editor):
    # используем на прямую последнюю версию моделей, из-за проблем создание пользователя из исторического User

    # Bot = apps.get_model("shop_bot_app", "Bot")
    # User = apps.get_model("auth", "User")
    # Group = apps.get_model("auth", "Group")
    # BotAdministratorProfile = apps.get_model("shop_bot_app", "BotAdministratorProfile")

    group_name = 'bot_administrator_group'
    group = Group.objects.filter(name=group_name).get()
    bots = list(Bot.objects.filter(administrator__isnull=True))
    for bot in bots:
        username = '%s%s' % (bot.name, 'Administrator')
        password = User.objects.make_random_password()

        user = User.objects.create_user(username=username, password=password, is_staff=True)
        BotAdministratorProfile.objects.create(user_id=user.id)
        user.groups.add(group)
        bot.administrator = user
        bot.save()
        print 'Created "%s" user' % username


def fake_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0023_auto_20170308_0704'),
    ]

    operations = [
        migrations.RunPython(create_bot_administrator, fake_reverse),
    ]
