# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0024_auto_20170308_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Bot'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
