# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0025_auto_20170308_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postponedpost',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Bot'),
        ),
    ]
