# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 22:39
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import shop_bot_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0027_auto_20170308_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=shop_bot_app.models.rename_and_upload_path),
        ),
    ]
