# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-08 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0033_bot_bot_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_support',
            field=models.ForeignKey(blank=True, help_text='\u0427\u0435\u043b\u043e\u0432\u0435\u043a, \u043a\u043e\u0442\u043e\u0440\u043e\u043c\u0443 \u0431\u0443\u0434\u0443\u0442 \u043f\u0435\u0440\u0435\u043d\u0430\u043f\u0440\u0430\u0432\u043b\u044f\u0442\u044c\u0441\u044f \u0432\u0441\u0435 \u0432\u043e\u043f\u0440\u043e\u0441\u044b \u0438\u0437 \u0431\u043e\u0442\u0430', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Buyer'),
        ),
    ]
