# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0035_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Bot'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_bot_app.Buyer'),
        ),
    ]
