# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0036_auto_20170410_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, help_text='\u0410\u0440\u0442\u0438\u043a\u0443\u043b', max_length=255, null=True),
        ),
    ]
