# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 22:30
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import shop_bot_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0038_auto_20170418_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=shop_bot_app.models.faq_path),
        ),
    ]
