# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0040_auto_20170419_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='botbuyermap',
            name='dialog_with_support',
            field=models.TextField(null=True),
        ),
    ]
