# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 22:59
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import shop_bot_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0041_botbuyermap_dialog_with_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=shop_bot_app.models.postponed_post_path, verbose_name='\u0424\u043e\u0442\u043e \u0434\u043b\u044f \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
    ]
