# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import arrow


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0042_postponedpost_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='botbuyermap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=arrow.now().replace(days=-7).datetime), # поставим все старым юзерам время создания 7 дней назад
            preserve_default=False,
        ),
    ]
