# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot_app', '0044_botbuyermap_blocked_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botbuyermap',
            old_name='blocked_by_user',
            new_name='is_blocked_by_user',
        ),
    ]
